sudo: false

language: python

matrix:
  include:
    - python: "2.7_with_system_site_packages"
      env: COVERALLS=1
    - python: "3.4"
      env: COVERALLS=0

install:
  - pip install coveralls enum34 setuptools six future sortedcontainers requests PyYAML nose

script:
  - python setup.py build
  - if [ $COVERALLS = 1 ]; then
      coverage run --source=odml2 setup.py test && coverage report -m;
    else
      python setup.py test;
    fi;

after_success:
  - if [ $COVERALLS = 1 ]; then
      coveralls;
    fi;
